baseURL = 'https://greasycat.github.io/'
languageCode = 'en-us'
title = 'A Greasy Site'
theme = "anubis"
publishDir = 'docs'

canonifyURLs = true

[[menu.main]]
identifier = "all"
name= "All"
title= "All"
url= "/"
weight= 1

[[menu.main]]
identifier = "logs"
name= "Logs"
title= "Logs"
url= "/posts/logs/"
weight= 4

[[menu.main]]
identifier = "tools"
name= "Tools"
title= "Tools"
url= "/posts/tools/"
weight= 3

[[menu.main]]
identifier = "brain"
name= "Brain"
title= "Brain"
url= "/posts/brain/"
weight= 2

[[menu.main]]
identifier = "code"
name= "Code"
title= "Code"
url= "/posts/code/"
weight= 1


[[params]]
author= "GreasyCat"
# avatar= "/images/me.png" # used for microformats
description= "PURRRING POWERRR!"
style="auto"
copyCodeButton=true
disableSummary=false
readMore=true
paginationSinglePost=true

[[params.social]]
id = "github"
url = "https://github.com/greasycat/greasycat.github.io"


[markup.goldmark.renderer]
unsafe= true # enable raw HTML in Markdown
